### ISSUE TITLE
"resource_group_id" is recognised as an unsupported argument

### ISSUE THREAD

**Issue by Xxiao-ma** [terraform-ibm-modules/terraform-ibm-secrets-manager-iam-engine#52]
### Affected modules

* iam_secrets_engine- "terraform-ibm-modules/secrets-manager-iam-engine/ibm"

### Terraform CLI and Terraform provider versions

* Terraform version:1.54.0
* Provider version:1.62

### Terraform output

```
│ Error: Unsupported argument
│ 
│   on main.tf line 51, in module "iam_secrets_engine":
│   51:   resource_group_id    = module.resource_group.resource_group_id
│ 
│ An argument named "resource_group_id" is not expected here.
```
### Expected behavior
In the [usage](https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager-iam-engine/tree/main?tab=readme-ov-file#usage), `resource_group_id` is a valid input argument but actually it's not. If resource group id is not supported anymore this line in the readme should be removed.

### Steps to reproduce (including links and screen captures)

1. Run `terraform plan`

### Anything else

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by ocofaigh** [comment]
The usage was incorrectly documented. PR to fix: https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager-iam-engine/pull/53

@Xxiao-ma FYI, all valid inputs can be seen at https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager-iam-engine?tab=readme-ov-file#inputs
