### ISSUE TITLE
Use secret manager example in a test

### ISSUE THREAD

**Issue by kierramarie** [terraform-ibm-modules/terraform-ibm-secrets-manager-iam-engine#82]
### Description

A private secret manager example exists in this repo and needs to be used in a test in the pr_test.go.

### New or affected modules

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by ocofaigh** [comment]
@kierramarie There is already a test for this example. See https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager-iam-engine/blob/cc28056a71666cd70d0db460d16c42c3e80ef6b5/tests/pr_test.go#L49
